#!/usr/bin/env -S python3 -u

import argparse
import json
import select
import socket

from ipAddress import Ip
from route import Route


# Should constantly be reading from the sockets to make sure we receive all messages
# handle multiple sockets using select or poll
# handle json messages based on type, source, destination, and message

class Router:
    """
    The class of the router that can send data according to the routing table
    It can also update and withdraw the routing accordingly.
    """
    def __init__(self, asn, connections):
        """
        The init function of the router class
        :param asn: the router number
        :param connections: the connection to the other router
        """
        print("Router at AS %s starting up" % asn)
        self.asn = asn
        self.relations = {}
        self.sockets = {}
        self.ports = {}
        self.neighbors = []
        self.routing_table = []
        self.routing_table_no_aggregation = []
        self.messageCopy = []

        # Create a socket for each connection
        for relationship in connections:
            port, neighbor, relation = relationship.split("-")

            self.neighbors.append(neighbor)

            self.sockets[neighbor] = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.sockets[neighbor].bind(('localhost', 0))
            self.ports[neighbor] = int(port)
            self.relations[neighbor] = relation
            self.send(neighbor,
                      json.dumps({"type": "handshake", "src": self.our_addr(neighbor), "dst": neighbor, "msg": {}}))

    def our_addr(self, dst):
        """
        Return our address according to the destination ip
        :param dst: string of the destination to send the packet
        :return: the string of our router ip
        """
        quads = list(int(qdn) for qdn in dst.split('.'))
        quads[3] = 1
        return "%d.%d.%d.%d" % (quads[0], quads[1], quads[2], quads[3])

    def send(self, network, message):
        """
        The function send the message to the given ip
        :param network: string of the destination
        :param message: string of the message to be sent
        :return: none
        """
        self.sockets[network].sendto(message.encode('utf-8'), ('localhost', self.ports[network]))

    def update(self, message):
        """
        Accept a message(json) and update the routing table
        :param message: json object of the update
        :return: none
        """
        self.messageCopy.append(message)

        route = Route(message)
        self.routing_table.append(route)
        self.check_aggregation(route)
        self.routing_table_no_aggregation.append(route)
        as_path = route.ASPath.copy()
        as_path.insert(0, self.asn)

        # if from customer, send to all neighbors
        if self.relations[message["src"]] == "cust":
            # send to all neighbors
            for neighbor in self.neighbors:
                if neighbor != message["src"]:
                    self.send(neighbor,
                              json.dumps({"msg": route.copy(as_path),
                                          "src": self.our_addr(neighbor), 'dst': neighbor, 'type': 'update'}))
        else:
            for neighbor in self.neighbors:
                if neighbor != message["src"] and self.relations[neighbor] == "cust":
                    self.send(neighbor,
                              json.dumps({"msg": route.copy(as_path),
                                          "src": self.our_addr(neighbor), 'dst': neighbor, 'type': 'update'}))

    def withdraw(self, message):
        """
        Withdraw a certain route in the routing table, and announce the withdraw
        to the other router.
        :param message: the json object given the information of the withdraw
        :return: none, remove the route from the table
        """
        self.messageCopy.append(message)

        # remove the route from the routing table
        for each in message["msg"]:
            for r in self.routing_table:
                if (r.source == message["src"] and r.network == each["network"]
                        and r.netmask == each['netmask']):
                    print("Removing route: ", r.network, r.netmask, r.ASPath, r.source)
                    self.routing_table.remove(r)
                    self.routing_table_no_aggregation.remove(r)
                    break

        for each in message["msg"]:
            print("Checking for route in another table: ", each["network"], each["netmask"])

            for route in self.routing_table_no_aggregation:
                print("Route in another table: ", route.source, route.network, route.netmask)

            for ra in self.routing_table_no_aggregation:
                if (ra.source == message["src"] and ra.network == each["network"]
                        and ra.netmask == each['netmask']):
                    self.routing_table_no_aggregation.remove(ra)
                    print("Removing route from another table: ", ra.network, ra.netmask, ra.ASPath, ra.source)

                    self.routing_table = []
                    for route in self.routing_table_no_aggregation:
                        self.routing_table.append(route)

                    print("routing table: ", self.routing_table)
                    # Aggregate the routes again
                    for route in self.routing_table:
                        self.check_aggregation(route)


        # if from customer, send to all neighbors
        if self.relations[message["src"]] == "cust":
            for neighbor in self.neighbors:
                if neighbor != message["src"]:
                    self.send(neighbor, json.dumps({"msg": message["msg"], "src": self.our_addr(neighbor),
                                                    "dst": neighbor, "type": "withdraw"}))

        else:
            for neighbor in self.neighbors:
                if neighbor != message["src"] and self.relations[neighbor] == "cust":
                    self.send(neighbor, json.dumps({"msg": message["msg"], "src": self.our_addr(neighbor),
                                                    "dst": neighbor, "type": "withdraw"}))

        return

    def dump(self, message):
        """
        Send the copy of the current routing table to the router send the dump message
        :param message: a json object which is the dump message
        :return: none
        """
        dump = []
        for route in self.routing_table:
            route_dump = route.dump()
            route_dump['peer'] = route.source
            # Update the peer field from the message_copy with the source IP of the router that sent "update" message
            # for msg in self.messageCopy:
            #     if (((msg["type"] == "update" and route_dump['network'] == msg["msg"]["network"]) and
            #          route_dump['ASPath'] == msg["msg"]["ASPath"]) and
            #             route_dump['netmask'] == msg["msg"]["netmask"]):
            #         route_dump['peer'] = msg["src"]
            #
            #         print("Peer: ", route_dump['peer'])
            #         break

            dump.append(route_dump)

        table_msg = json.dumps(
            {"src": self.our_addr(message["src"]), "dst": message["src"], "type": "table", "msg": dump})

        self.send(message["src"], table_msg)

    def check_aggregation(self, route):
        """
        Check if any route in the routing table can be aggregate
        :param route: route to check
        :return: none, modify inside the routing table
        """
        while True:
            aggregated = False
            for r in self.routing_table:
                for other in self.routing_table:
                    if other != r and r.is_adjacent(other):
                        print("Aggregating routes: ", r.network, r.netmask, " and ", other.network, other.netmask)
                        self.routing_table.remove(other)
                        print("removing route: ", other.network, other.netmask)

                        r_copy = r.copy_route()
                        r_ip = r.ip.network_to_int()
                        o_ip = other.ip.network_to_int()

                        if r_ip > o_ip:
                            r_copy.network = other.network

                        r_copy.netmask = r_copy.ip.shift_ip_and_mask()
                        r_copy.ip = Ip(r_copy.network, r_copy.netmask)

                        self.routing_table.remove(r)
                        self.routing_table.append(r_copy)

                        print("New route: ", r.network, r.netmask)
                        aggregated = True
                        break
                if aggregated:
                    break
            if not aggregated:
                break

    def check_route(self, dst):
        """
        Chcek which route in the routing is the best match for the destination ip
        :param dst: destination ip for the data message
        :return: The best route class to send to
        """
        longest = -1
        best_route = None

        for route in self.routing_table:
            match_length = route.ip.belong_to(dst)

            # Skip routes that don't match the destination IP address
            if match_length < 0:
                continue

            if match_length > longest:
                longest = match_length
                best_route = route
            elif match_length < longest:
                continue
            else:
                if not best_route:
                    continue
                if best_route.localpref > route.localpref:
                    continue
                elif best_route.localpref < route.localpref:
                    best_route = route
                else:
                    if best_route.selfOrigin and not route.selfOrigin:
                        continue
                    elif not best_route.selfOrigin and route.selfOrigin:
                        best_route = route
                    else:
                        if len(best_route.ASPath) < len(route.ASPath):
                            continue
                        elif len(best_route.ASPath) > len(route.ASPath):
                            best_route = route
                        else:
                            if best_route.source_to_int() < route.source_to_int():
                                continue
                            else:
                                best_route = route
        return best_route

    # respond that there is no route to this destination
    def no_route(self, outgoing_ip, destination):
        """
        The function will send the no route message to the given port
        and the gien destination of the no route message
        :param outgoing_ip: the next hop route's ip
        :param destination: the no route final destination
        :return: None
        """
        self.send(outgoing_ip, json.dumps({"src": self.our_addr(outgoing_ip), "dst": destination, "type": "no route",
                                           "msg": {}}))

    def run(self):
        """
        Main running function for the router
        :return: none
        """
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                k, addr = conn.recvfrom(65535)
                srcif = None
                for sock in self.sockets:
                    if self.sockets[sock] == conn:
                        srcif = sock
                        break
                msg = k.decode('utf-8')
                print("Received message '%s' from %s" % (msg, srcif))

                message = json.loads(msg)
                msg_type = message['type']

                # type = update
                if msg_type == "update":
                    self.update(message)

                # type = data
                elif msg_type == "data":
                    # forward the message to the destination
                    dst = message['dst']

                    best_route = self.check_route(dst)
                    # if the ip is not in the routing table return the msg with no route
                    if not best_route:
                        self.no_route(srcif, message["src"])

                    elif self.relations[srcif] == "cust" or self.relations[best_route.source] == "cust":
                        self.send(best_route.source, msg)
                        print("Forwarding message to %s for port %s" % (dst, best_route.source))

                    else:
                        print("the message is dropped!")

                elif msg_type == "dump":
                    self.dump(message)

                elif msg_type == "withdraw":
                    self.withdraw(message)

                else:
                    print("Unknown message type: %s" % msg_type)
        return


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='route packets')
    parser.add_argument('asn', type=int, help="AS number of this router")
    parser.add_argument('connections', metavar='connections', type=str, nargs='+', help="connections")
    args = parser.parse_args()
    router = Router(args.asn, args.connections)
    router.run()
